### ISSUE TITLE
Is it possible to return a blob via stdout

### ISSUE THREAD

**Issue by toomanylogins** [foresterre/sic#1547]
Rather than write an output file to temp can a processed image be returned via stdout ?

I am running latest 0.22 on a folder as follows.

sic --glob-input "G:/Temp/*.{jpg, jpeg, png}" --glob-output "C:/Users/Paul/AppData/Local/Temp/youdocms" --resize 200 200

after about 70 files I get format error but no file ref. The directory does inc files other than jpg,jpeg and png. 

Thanks
Paul

**Comment by foresterre** [comment]
For individual files, you can do the following to get a blob:

```
sic --output-format png --input .\resources\logo\sic_500.jpg --resize 200 200 >> out.png
```

Files which use `--glob-input` currently always require `--glob-output` to be present, and this mode doesn't currently support stdout.

Looking at your paths, I think you're on Windows; as a workaround you could use the following Powershell:

```
Get-ChildItem -Recurse ".\resources" -Include "*.jpg","*.jpeg","*.png" | ForEach-Object { sic --input $_.FullName --output somedir/$($_.Name) --resize 200 200 }
```

For your directories:

```
Get-ChildItem -Recurse "G:/Temp" -Include "*.jpg","*.jpeg","*.png" | ForEach-Object { sic --input $_.FullName --output C:/Users/Paul/AppData/Local/Temp/youdocms/$($_.Name) --resize 200 200 }
```

**Comment by toomanylogins** [comment]
Thank you for reply. I have this working via blob or file and looping through the files. Not getting the format error. I will try to track down the file that is causing the problem if I try to process a directory.

**Comment by foresterre** [comment]
> > after about 70 files I get format error but no file ref. The directory does inc files other than jpg,jpeg and png.
> 
> That's not good! I should improve the error message and/or add a flag to allow for (silent/with a warning to stderr) failures.

I added error context in #1555
