### ISSUE TITLE
Operation Range of Units

### ISSUE THREAD

**Issue by toomanylogins** [foresterre/sic#1581]
Is there any information on the range of units for each operation eg. Blur real is that between 1-10 ? whereas brighten int is that 1-10 or 1-100. 
Thanks
Paul

**Comment by foresterre** [comment]
> Is there any information on the range of units for each operation eg. Blur real is that between 1-10 ? whereas brighten int is that 1-10 or 1-100. Thanks Paul

The parameter of a blur is the standard deviation of the Gaussian kernel applied to your image. The values of the standard deviation can be anything between `0` and `Inf ⋅ σ` in theory. In practice, we're both limited by the 32 bit floating point number we use, and the observation that large values will completely wipe out any meaningful projections. I would experiment with values between `0.1σ` and `5σ`.

The parameter of brighten is limited by the type of pixel used. When applying the brighten image operation, the value of the given parameter is added to each channel of the pixel (usually red, green, blue), except for the alpha channel. Negative values will instead darken the image. Note that the added values are clamped. The range of values depends on the amount of bits per channel per pixel. Most commonly, each channel will have 8 bits, so values from -256 to 255 can make sense, depending on the current value of each channel of the pixels.
