### ISSUE TITLE
[HELP] Running sic on a managed webserver

### ISSUE THREAD

**Issue by felixranesberger** [foresterre/sic#1737]
Hi, I want to run sic on my managed webserver, where a lot of default dependencies are not available.

The `sic-x86_64-unknown-linux-gnu-v0.22.4.tgz` release does not work, so I think I need a `x86_64-unknown-linux-musl` binary, because musl doesn't link the dependencies?

I'm pretty new to rust and tried to follow the following blog article, but to no success.
https://betterprogramming.pub/cross-compiling-rust-from-mac-to-linux-7fad5a454ab1

Do you think I can solve this issue by running a musl build? 

Thanks for your help in advance!

**Comment by foresterre** [comment]
Probably musl can work.

For this, make sure you have the musl tools installed.
On Ubuntu (not sure about mac), you can install these with `apt install musl-tools`.
Then, you need the musl target for your current Rust toolchain: `rustup target add x86_64-unknown-linux-musl`.
Finally, build a sic binary by running: `cargo build --release --target x86_64-unknown-linux-musl`

For your convenience (but feel free to build your own of course!), I made a build with musl ([latest](https://github.com/foresterre/sic/commit/7f5da420480862109463f632eaba0a219904edfa) commit though!).

[sic-x86_64-unknown-linux-musl-0.22.4+7f5da4.zip](https://github.com/foresterre/sic/files/13357048/sic-x86_64-unknown-linux-musl-0.22.4%2B7f5da4.zip)

**Comment by felixranesberger** [comment]
Due to the old `glibc` version (`2.31`), we had to build a `musl` version inside a docker container (as you suggested). 
It works for now, but I'll make sure that my hoster updates the outdated version and then I'll switch to your version.

Thanks for the quick response 👍
