### ISSUE TITLE
Fix warning on taking reference of vector instead of slice 

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#187]
> Warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
  --> sic_image_engine/src/engine.rs:99:42
   |
99 |     pub fn ignite(&mut self, statements: &Program) -> Result<&DynamicImage, Box<dyn Error>> {
   |                                          ^^^^^^^^
   |
   = note: `#[warn(clippy::ptr_arg)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

**Comment by clanghout** [comment]
on it :smiley:
