### ISSUE TITLE
Use the Read and Write from the image crate instead of our custom reader and writer

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#201]
depends on `image 0.22.3`, #199

in particular, refactor (using Read/Write implementation from image crate 0.22.3):
* [load](https://github.com/foresterre/sic/blob/master/sic_io/src/load.rs): use Read from image crate if that would work with gif frame selection
* [save](https://github.com/foresterre/sic/blob/master/sic_io/src/save.rs#L7): this module doesn't use the general (Read or) Write trait at all. Instead it currently defines  `ExportMethod`. This should be refactored to use the Write trait instead. 

_If there are questions, feel free to ask! =)_

**Comment by luxrck** [comment]
Hello, @foresterre , could I take this up?

**Comment by foresterre** [comment]
Thank you for these contributions. Today I won't have time to look at this, but tomorrow I should have some.
