### ISSUE TITLE
Great tool, with watermark function will be better

### ISSUE THREAD

**Issue by EasiestSoft** [foresterre/sic#335]
I searched many image processing tools in Rust, Go, C...and found sic is great

One of import functions in sic is that it can apply multiple operations in a single command line command

Is it possible to add a watermark function to sic？

I currently use https: //github.com/Eun/watermark with sic, but if I can use the watermark function in _apply-operations_ in sic, that would be great

**Comment by foresterre** [comment]
This is something I definitely do want to add. I'll look into implementing it in the near future.
