### ISSUE TITLE
Add --skip-unsupported-extension to skip unwanted paths matching a glob

### ISSUE THREAD

**Issue by MuLeonis** [foresterre/sic#494]
`sic's` glob path implementation currently doesn't filter non-image files. This means that if a (glob) path contains any unsupported file path, eventually an unsupported file format error will be thrown. This may be unwanted as `sic` targets specific file types (namely images), and a folder may contain many other files. While the glob paths themselves are a tool to filter out unwanted files, the input glob can be made simpler by having the glob walker (iterator) skip files which are almost certainly unwanted (namely non-image files).

By filtering to known image file extensions, we attempt to prevent a user from having to specify very complex and too specific globs.

part of #407 (first step)

**Comment by foresterre** [comment]
Thanks I will have a look at it soon! :)
