### ISSUE TITLE
image operation `image::imageops` => add `horizontal-gradient`

### ISSUE THREAD

**Issue by foresterre** [foresterre/sic#571]
introduced in 0.23.9, #569

Thank you for taking the time to look at this feature request. If you want to help by implementing the feature, thanks!; I've added some ideas on how to implement it below. If there are questions, always feel free to ask!

**PR 1:**

* [ ] Create an issue for this step, e.g. titled `Image Operation engine: add horizontal-gradient`

* [ ] Implement [horizontal-gradient](https://docs.rs/image/0.23.10/image/imageops/fn.horizontal_gradient.html) operation 
  * [ ] Add an `ImgOp` for the operation: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_image_engine/src/lib.rs#L16
  * [ ] Implement the operation: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_image_engine/src/engine.rs#L110
  * [ ] Add tests to verify the operation works as expected. You can use the examples set by other operations. Consider using [parameterized](https://github.com/foresterre/parameterized#examples) tests for similar test cases; the dependency should already exist.

**PR 2 part 1:**

* [ ] Create an issue for this step, e.g. titled `Image Operation parsing: add horizontal-gradient`

* [ ] Consider syntax which works for both `cli ops` and the `--apply-operations` script. This means that an operation should be able to be parseable without introducing ambiguity with both the  the Pest parser used for `apply-operations` script, as well as the cli ops parser used for the cli interface. Additionally, this last syntax should also be compatible with Clap, which is used for the general cli interface (but is inconvenient for the cli ops). The next points will describe the exact steps to implement these parsers. I would recommend doing both in one go to ensure compatibility with each other. You may consider dividing the actual work to multiple PR's, but doing so is optional.  

**PR 2 part 2:**

* [ ] Implement cli ops and `--apply-operations` script parsers

* [ ] cli ops:
    * [ ] Add an OperationId for the operation: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_cli_ops/src/operations.rs#L18
    * [ ] Implement `takes_number_of_arguments`: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_cli_ops/src/operations.rs#L66
    * [ ] Implement `create_instruction`: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_cli_ops/src/operations.rs#L113
        *  [ ] To recognise values, we used the [ParseInputsFromIter](https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_parser/src/value_parser.rs#L41), which will be re-usable when implementing the Pest parser in part 3. Whether you should add a new type and implementation depends on the arguments required for the operation. If the operation arguments are complex, you can use a wrapper ([example](https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_image_engine/src/wrapper/draw_text_inner.rs#L6), instead of an argument tuple or primitive type.

**PR 2 part 3:**

* [ ] `--apply-operations` script:
    * [ ] Add operation to Pest: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_parser/src/grammar.pest#L76
    * [ ] Add a Rule for the operation to the Pest PEG file: https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_parser/src/grammar.pest#L36
    * [ ] Match the Rule you just made against the [Instrs](https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_image_engine/src/engine.rs#L72), and transform the Pest Pair(s) to the `ImgOp` you added at the start of this issue (This `ImgOp` is wrapped in by the `Instr` enum): https://github.com/foresterre/sic/blob/33acebfd52b7b8678c433de57513c862695fc30c/components/sic_parser/src/rule_parser.rs#L26. Here you can re-use the value parser used in part 2.
    * [ ] Add tests to verify parsing works as expected. You can use the examples set by other operations. Consider using [parameterized](https://github.com/foresterre/parameterized#examples) tests for similar test cases; the dependency should already exist.

**Comment by MustafaSalih1993** [comment]
Hello, is this still available, I'd like to implement it

**Comment by MustafaSalih1993** [comment]
> It is; if you have questions feel free to ask :)

Thanks!
i have implemented the feature successfully but I'm suspicious to commit it because of that the
(horizontal/vertical)-gradient functions provided by image crate _**Fill**_ the input image with gradient color, but not overlaying the input-image with a gradient, is this the expected output behavior of this feature request?
PS: sorry for my bad English, I'm not a native English speaker.

**Comment by foresterre** [comment]
> i have implemented the feature successfully

Nice work!

> but I'm suspicious to commit it because of that the
> (horizontal/vertical)-gradient functions provided by image crate _**Fill**_ the input image with gradient color, but not overlaying the input-image with a gradient,

> basically now the command:`sic -i input.png -o out.png -x "horizontal-gradient rgba(255, 0, 0, 255) rgba(0, 0, 255, 255)"` outputs an image with Only a gradient from red to blue, but not putting the gradient colors as a filter for the input image. is this the expected output behavior of this feature request?

If I understand the `image` docs correctly, it indeed fills an image buffer with a certain gradient. We can do the overlay part ourselves. 

One way to approach this is by creating a new `ImageBuffer` on which the gradient is applied. Then we can [interpolate](https://ciechanow.ski/alpha-compositing/) the buffer in the `SicImage` with this gradient.

**Comment by MustafaSalih1993** [comment]
ah i see, thanks for your help! i will make a pr as soon as i finish, i think i have to read `image` crate documentation more and teach myself more about image processing.

**Comment by MustafaSalih1993** [comment]
Progress: it works!

**Comment by foresterre** [comment]
closed by #840 
TODO's:
- Add to readme and changelog, see #843
