### ISSUE TITLE
Publish on Homebrew for MacOS & Linux 🍺

### ISSUE THREAD

**Issue by TGotwig** [foresterre/sic#606]
I could create formula for publishing on MacOS and Linux 🙂🍺

**Comment by foresterre** [comment]
Hey, thanks for showing interest!

I personally don't use homebrew, nor do I know anything about making such formulas, so feel free to make and publish one!

If you do need anything from me, please let me know!

**Comment by TGotwig** [comment]
Okay cool! No problem! 🙂
You can build two archives with that Makefile from the Pull-Request above,
please upload them there https://github.com/foresterre/sic/releases/tag/v0.14.0 ⬆️

**Comment by TGotwig** [comment]
There is a official vendors tap which is called sic,
not really sure how to deal with that,
maybe somehow untap the official one and tap our one,
I tried few things but it doesn't work 🙈

**Comment by TGotwig** [comment]
Ahh now it works 🚀
```
brew tap tgotwig/linux-sic
brew install tgotwig/linux-sic/sic
```

**Comment by foresterre** [comment]
Thanks! I left a comment on the PR (I am not able to cross compile the macOS version). 

After that works, I will checkout the 0.14 release and compile both targets and upload the archives to the release page. I think I will also make a 0.15 release with the current state, and move the remaining 0.15 items to 0.16.
