### ISSUE TITLE
Add crop command

### ISSUE THREAD

**Issue by clanghout** [foresterre/sic#64]
- Add crop to `--script`
- Crop is not the same as resize,
- i.e. it selects a sub canvas within the image canvas and crops to that sub canvas

**Comment by foresterre** [comment]
Thanks for noticing!

Planned for 0.9.0

Possible syntax options:
1) `crop xa ya xb yb` with 
    - `xa: top left corner x-coordinate`
    - `ya: top left corner y-coordinate`
    - `xb: bottom right corner x-coordinate`
    - `ya: bottom right corner y-coordinate`

2) `crop xa ya w h` with 
    - `xa: bottom left corner x-coordinate`
    - `ya: bottom left corner y-coordinate`
    - `w: width of the subimage view`
    - `h: height of the subimage view`

or variations on the options above.

Probably (1) makes the most sense as its analogical to cropping in most image editors like Paint.

**Comment by foresterre** [comment]
Implemented in #83.
