### ISSUE TITLE
Shell completions as release artifacts

### ISSUE THREAD

**Issue by orhun** [foresterre/sic#785]
Hey! [AUR](https://aur.archlinux.org/packages/?O=0&K=sic-image-cli) maintainer of `sic` here.

I realized that `sic` stopped having shell completions (`shell_completions.zip`) as a release artifact after `0.15.0` release. It isn't a problem for [sic-image-cli](https://aur.archlinux.org/packages/sic-image-cli/) and [sic-image-cli-git](https://aur.archlinux.org/packages/sic-image-cli-git/) packages (since I generate them via `cargo run --example gen_completions`) but [sic-image-cli-bin](https://aur.archlinux.org/packages/sic-image-cli-bin/) (binary package) is unfortunately [no longer able to install](https://aur.archlinux.org/cgit/aur.git/commit/?h=sic-image-cli-bin&id=a8d9876821aa2a4d01e7d0948379f21c76ef7733) shell completions because it was actually using the `.zip` file.

Do you consider to bring it back for the {current,upcoming} release(s)?

**Comment by foresterre** [comment]
Of course! I completely forgot to generate them, because I forgot to include them into my release packing tool, apologies!

**Comment by orhun** [comment]
Ah, nice! I released a new version (`0.16.1-2`) of [sic-image-cli-bin](https://aur.archlinux.org/packages/sic-image-cli-bin/) which [contains the shell completions](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=sic-image-cli-bin&id=bb7d8e734eb7cc5b8c43076b09082384aae0b652).
Thanks!
